#!/bin/bash

TOML=/etc/confd/conf.d/haproxy.toml
TMPL=/etc/confd/templates/haproxy.tmpl
APP=$(getenv APP)
SERVICE=$(getenv SERVICE)
PUBLIC_DOMAIN=$(getenv PUBLIC_DOMAIN)
HOST=$(getenv HOST_IP)
HOST_IP=${HOST:-172.17.0.1}

sed -i -e "s#SERVICE_NAME#$APP-$SERVICE#g" -e "s#PUBLIC_DOMAIN#$PUBLIC_DOMAIN#g" $TMPL

for ((i=0; i<120; i++)); do
  confd -onetime -node $HOST_IP:2379 -config-file ${TOML} && break
  echo "[haproxy] waiting for confd to create initial haproxy configuration."
  sleep 1
done
