#!/bin/sh

TOML=/etc/confd/conf.d/haproxy.toml                                                                                                                                         
TMPL=/etc/confd/templates/haproxy.tmpl                                                                                                                                      
TMPL_FIRST=/etc/confd/templates/haproxy.tmpl.orig                                                                                                                           
                                                                                                                                                                            
config=$(cat /etc/haproxy/haproxy.json)                                                                                                                                     
configq=$(echo -e $config |sed -e 's/\"/\\\"/g')                                                                                                                            
                                                                                                                                                                            
LBSTRING="{{ \$configs := \"$configq\" }}"                                                                                                                                  
                                                                                                                                                                            
alias sedcmd=$(printf "sed -e '1i %q' $TMPL_FIRST > $TMPL" "$LBSTRING")                                                                                                     
                                                                                                                                                                            
sedcmd

for ((i=0; i<10; i++)); do
  confd -onetime -node $CSPHERE_NODE_IP:2379 -config-file ${TOML} && break
  echo "[haproxy] waiting for confd to create initial haproxy configuration."
  sleep 1
done
