#!/bin/bash

ETCD=$CSPHERE_NODE_IP:2379
CONFD=/bin/confd
TOML=/etc/confd/conf.d/haproxy.toml

echo "confd is now monitoring etcd for changes..."
exec ${CONFD} -watch -node ${ETCD} -config-file ${TOML}
