#!/bin/bash

# Start the Haproxy service using the generated config
# echo "[haproxy] starting haproxy service..."

check_haproxy() {
  while [ true ]; do
    ps ax|grep -q '/usr/sbin/haprox[y]' || exit 1
    sleep 10
  done
}

# maybe confd launched a haproxy process before me, avoid conflicting
old_pid=$(ps ax|grep '/usr/sbin/haprox[y]'|cut -c1-5)

[ -f /etc/haproxy/haproxy.cfg ] &&
/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -sf $old_pid

check_haproxy
